<?php

namespace Alumbrados\TownyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidentRepository extends EntityRepository
{
}
